version: '3.8'
services:

  db:
    image: 'postgres:13.7'
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: obtaining_citizenship
    ports:
      - "5432:5432"
    restart: unless-stopped

  app:
    image: 'valzhanov/migration-assistance-back:v1'
    container_name: app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/obtaining_citizenship
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

  app-front:
    image: 'valzhanov/migration-assistance-front:v1'
    container_name: app-front
    ports:
      - "8081:8081"
    depends_on:
      - app
    restart: unless-stopped
    stdin_open: true

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - data:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root1
      - MONGO_INITDB_ROOT_PASSWORD=root2
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - 8081:8085
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root1
      - ME_CONFIG_MONGODB_ADMINPASSWORD=root2
      - ME_CONFIG_MONGODB_SERVER=mongodb

volumes:
  data: {}

networks:
  default:
    name: mongodb_network
