
create table message
(
    id        int8 generated by default as identity,
    date_time timestamp,
    message   varchar(255),
    username  varchar(255),
    user_id   int8,
    primary key (id)
);

create table roles
(
    id   int4 generated by default as identity,
    name varchar(20),
    primary key (id)
);
create table user_roles
(
    user_id int8 not null,
    role_id int4 not null,
    primary key (user_id, role_id)
);
create table users
(
    id       int8 generated by default as identity,
    email    varchar(50),
    password varchar(120),
    username varchar(20),
    primary key (id)
);
create table users_messages
(
    user_id     int8 not null,
    messages_id int8 not null
);
alter table if exists users
    add constraint UKr43af9ap4edm43mmtq01oddj6 unique (username);
alter table if exists users
    add constraint UK6dotkott2kjsp8vw4d0m25fb7 unique (email);
alter table if exists users_messages
    add constraint UK_9ybe7v51r6kklm7ecxyu5glp unique (messages_id);
alter table if exists message
    add constraint FKpdrb79dg3bgym7pydlf9k3p1n foreign key (user_id) references users;
alter table if exists user_roles
    add constraint FKh8ciramu9cc9q3qcqiv4ue8a6 foreign key (role_id) references roles;
alter table if exists user_roles
    add constraint FKhfh9dx7w3ubf1co1vdev94g3f foreign key (user_id) references users;
alter table if exists users_messages
    add constraint FK7wyvj23qj3bra1snwrhwvouwt foreign key (messages_id) references message;
alter table if exists users_messages
    add constraint FK3tpfu7mudlhpcrh6xufdkexha foreign key (user_id) references users;

INSERT INTO roles
VALUES (1, 'ROLE_USER'),
       (2, 'ROLE_MODERATOR'),
       (3, 'ROLE_ADMIN');


-- password 123456
INSERT INTO users (email, password, username) VALUES ('root','$2a$10$I5ZTp/vC2Stw76hfERLsp.ilIauxLbssRLmP4Zi1VHrQ33fFsmbOi','root'),
                                                     ('user','$2a$10$I5ZTp/vC2Stw76hfERLsp.ilIauxLbssRLmP4Zi1VHrQ33fFsmbOi','user');
INSERT INTO user_roles VALUES (1,1),(1,2),(2,1);